[package]
name = "parva_os"
version = "0.0.1"
authors = ["Francesco Giannice <giannice.developer@gmail.com>"]
edition = "2024"
readme = "README.md"
license = "GPL-3.0-only"

[dependencies]
bootloader = "0.9"
volatile = "0.2.6"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]