[package]
name = "parvaos"
version = "0.0.1"
authors = ["Francesco Giannice <giannice.developer@gmail.com>"]
edition = "2024"
readme = "README.md"
license = "GPL-3.0-only"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
